### ISSUE TITLE
Add tests to prove delayed retries work properly

### ISSUE THREAD

**Issue by ReneVolution** [ReneVolution/memory_task_queue#1]
We need a test that proves that e.g. a delay of `3s` actually waits for 3 seconds.

**Comment by OmerAhmedKhan** [comment]
Looking...

**Comment by OmerAhmedKhan** [comment]
Done https://github.com/ReneVolution/memory_task_queue/pull/2

**Comment by ReneVolution** [comment]
Well done 👍. Thanks.
